# All ACDC data sets

Table \@ref(tab:taball) contains all data sets that are part of the Attentional Control Data Collection at the time of manuscript submission. This version of the data base is maked by a git tag, and the git repository for the tag is [linked here](https://github.com/jstbcs/acdc-database/tree/submission1). The table is ordered by dataset ID and study, and contains the number of trials per condition and participant, and the number of participants. Additionally, three reliability estimates are included: The signal-to-noise ratio, $\gamma$, the split-half reliability for 2000 random splits, $\rho$, and the corrected split-half reliability using the Spearman-Brown formula, $\rho^*$.


(ref:mytablenote) $\gamma =$ signal-to-noise ratio; $I =$ number of participants; $K =$ number of trials per condition; $\rho =$ split-half reliability coefficient; $\rho^* =$ Spearman-Brown corrected reliability coefficient.


(ref:tabref1) @chetverikov2017blame
(ref:tabref2) @enkavi2019large
(ref:tabref3) @hedge2018reliability
(ref:tabref4) @kucina2023calibration
(ref:tabref5) @loeffler2022common
(ref:tabref6) @ebersole2016many
(ref:tabref7) @pratte2010exploring
(ref:tabref8) @mermet2018should
(ref:tabref9) @stahl2014behavioral
(ref:tabref10) @tang2023dual
(ref:tabref11) @vonbastian2016evidence
(ref:tabref12) @whitehead2019cognitive


```{r taball, results='asis', eval = T}
reldat <- reldat[, c(1:3, 5:6, 4, 7:8)]
linesep <- ifelse(reldat$publication_code[1:(nrow(reldat) - 1)] == reldat$publication_code[2:nrow(reldat)], '', '\\addlinespace')
publication_code = gsub('[_]', '', unique(dat$publication_code))
# publication_code
# nrow(reldat)

stub_indents = list(1, 2:4, 5:8, 9:13, 14:16, 17:37, 38:41, 42:49, 50:51, 52, 53:55, 56:64)
names(stub_indents) <- paste0("(ref:tabref", 1:length(publication_code), ")")

apa_table(reldat[,-2]
          , caption = "All datasets currently in ACDC."
          , note = "(ref:mytablenote)"
          , align = c("wl{3cm}", rep("c", 6))
          , digits = c(0,0,0,0,3,2,2)
          , col.names = c("ID", "Task name", "I", "K"
                          , "$\\gamma$", "$\\rho$", "$\\rho^*$")
          , longtable = T
          , font_size = "small"
          , stub_indents = stub_indents
          )
```
