---
title             : "Attentional Control Data Collection: An Open Data Resource for Attentional Control Research"
shorttitle        : "Attentional Control Data Collection"

author: 
  - name          : "TBD"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - "Conceptualization"
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"
  - name          : "TBD"
    affiliation   : "1,2"
    role:
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"
  - name          : "TBD"
    affiliation   : "1,2"
    role:
      - "Writing - Review & Editing"

affiliation:
  - id            : "1"
    institution   : "University of Amsterdam"
  - id            : "2"
    institution   : "University of Heidelberg"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["lab.bib", "r-references.bib"]

floatsintext      : no
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

header-includes:
  - \usepackage{mathrsfs}
  - \usepackage[makeroom]{cancel}
  - \usepackage{pcl}
  - \usepackage{setspace}\doublespacing
  - \usepackage{marginnote}
  - \newcommand{\readme}[1]{\emph{\marginnote{Julia} (#1)}}
  - \usepackage{pifont}
  - \usepackage{hyperref}
  - \usepackage{colortbl}
  - \hypersetup{colorlinks=true,urlcolor=blue,citecolor=black,linkcolor=black}

classoption       : "man"
output            : papaja::apa6_pdf
csl               : apa6.csl
---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```



# SQLight Data Base

## Data Base Structure

## Included Data

# Accessing the Data Base

## R-Package

## Queries and Output

# Example Analysis

## Reliability of Experimental Tasks

## A Closer Look at the Stroop Task

# Discussion


\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
